- name: Install, start and enable Apache 
  hosts: 10.118.0.3
  gather_facts: yes
  tasks:
    - name: Install Apache
      dnf:
        name: httpd
        state: latest
      when: ansible_pkg_mgr == "yum"

    - name: Start and Enable
      systemd:
        name: httpd
        state: started
        enabled: yes
      when: ansible_service_mgr == "systemd"